config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "articles#index"
  # Defines the root path route ("/")
  # root "articles#index"
  # get "/articles", to: "articles#index"
  # get "/articles/:id" , to: "articles#show"
  # get "/new" , to: "articles#new"
  # post "/create" , to: "articles#create"
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user! , except: [:index, :show]

  def index
    @articles = Article.all
    render "index"
  end

  def show
    @article = Article.find(params[:id])
    render "show"
  end

  def new
    @article = Article.new
    render "new"
  end

  # def create
  #   #render json: params
  #   @article = Article.new
  #   @article.title = params[:title]
  #   @article.body = params[:body]
  #   if @article.save
  #     redirect_to "/articles/#{@article[:id]}" , allow_other_host: true
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "Article Created Successfully.", status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article, notice: "Article Updated Successfully.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other, notice: "Article Deleted Successfully."
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_comment, only: [:update, :destroy]

  def new
    render partial: "form"
  end

  def create
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article), notice: "Comment Posted Successfully.", status: :see_other
  end

  def edit
    # @comment is set by before_action :set_comment
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to article_path(@article), notice: "Comment Updated Successfully.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    redirect_to article_path(@article), notice: "Comment Deleted Successfully.", status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def set_comment
    @comment = @article.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit class: "bg-gray-100 px-4 py-2 rounded hover:bg-gray-200" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>
    

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<h3><%= link_to "Add New Article", new_article_path %></h3>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<% if user_signed_in? %>
<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Delete", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you Sure you want to Delete the Article?" }, class: "text-red-500" %></li>
</ul>
<% end %>
<hr>
<h2>Comments</h2>
<div class="flex flex-row">
<div class="basis-1/2">
<%= render @article.comments %>
</div>
<div class="basis-1/4">
<h2>Add a Comment:</h2>
<%= render "comments/form", article: @article, comment: @article.comments.build %>
  </div>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter :</strong>
  <%= comment.commenter %><br> <%# &emsp;&emsp;&emsp;&emsp;%>
  <%= comment.created_at %>
</p>

<p>
  <strong>Comment</strong>
  <% if comment.created_at != comment.updated_at %>
    <i>(Edited)</i>
  <% end %>
  <strong>: </strong>
  <%= comment.body %>
</p>

<% if user_signed_in? %>
  <ul>
    <li><%= link_to "Edit", edit_article_comment_path(@article, comment) %></li>
    <li><%= link_to "Delete", article_comment_path(@article, comment), data: { turbo_method: :delete, turbo_confirm: "Are you Sure you want to Delete the Comment?" }, class: "text-red-500" %></li>
  </ul>
<% end %>
<br>

app/views/comments/_form.html.erb
<%= form_with model: [ article, comment ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, class: "your-css-class" %>
  </p>
  <p>
    <%= form.submit class: "bg-gray-100 px-4 py-2 rounded hover:bg-gray-200" %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form", article: @article , comment: @article.comments.find(params[:id])%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose m-10 p-10">
    <div class="">
    <%= link_to "Home" , root_path%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <% if user_signed_in? %>
        <%#= link_to "Profile" , edit_user_registration_path %>
        <%= button_to "Log Out" , destroy_user_session_path , method: :delete %>
      <% else %>
        <%= link_to "Log In" , new_user_session_path %>
        <%#= link_to "Sign Up" , new_user_registration_path %>
      <% end %>
    </div>
    <br>
    <%= yield %>

    </div>
  </body>
</html>